url = document.URL;
mwhite = "getchagb.com/mwhite";
mwalker = "getchagb.com/mwalker";
rmondello = "getchagb.com/rmondello";
getchabooks = "getchabooks.com";
url = url.replace(mwhite, getchabooks);
url = url.replace(mwalker, getchabooks);
url = url.replace(rmondello, getchabooks);
window.location = url;
